include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_use_of_protected_member: ignore
    invalid_use_of_visible_for_testing_member: ignore

linter:
  rules:
    prefer_const_constructors: false
