#!/bin/sh
# Cross-compile Go backend for Android arm64 into assets + jniLibs.
set -e
ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
export PATH="${PATH}:/usr/local/go/bin:${HOME}/go/bin"

ASSETS_DIR="$ROOT/app/android/app/src/main/assets/go"
JNI_DIR="$ROOT/app/android/app/src/main/jniLibs/arm64-v8a"
TOOLING_DIR="$ROOT/app/assets/go"

mkdir -p "$ASSETS_DIR" "$JNI_DIR" "$TOOLING_DIR"

echo "Building GOOS=android GOARCH=arm64 ..."
cd "$ROOT/backend"
CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build -trimpath -ldflags='-s -w' \
  -o "$ASSETS_DIR/ssh-ai-agent" ./cmd/server

cp -f "$ASSETS_DIR/ssh-ai-agent" "$JNI_DIR/libssh_ai_agent.so"
chmod 755 "$JNI_DIR/libssh_ai_agent.so"
cp -f "$ASSETS_DIR/ssh-ai-agent" "$TOOLING_DIR/ssh-ai-agent-arm64"
printf 'backend binary is generated by scripts/build-go-android.sh\n' > "$TOOLING_DIR/README.txt"

ls -la "$ASSETS_DIR/ssh-ai-agent" "$JNI_DIR/libssh_ai_agent.so"
file "$ASSETS_DIR/ssh-ai-agent" || true
echo "OK"
